### ISSUE TITLE
[rndstatus.py] Bot status is working again

### ISSUE THREAD

**Issue by regisssty** [Twentysix26/26-Cogs#31]
Tried to make a little changes and bot status is working again! 
From rndstatus.py

> Old:
>             if self.last_change == None: #first run
>                 self.last_change = int(time.perf_counter())
>                 if len(self.statuses) > 0 and (current_game in self.statuses or current_game == "None"):
>                     new_game = self.random_status(message)
>                     await self.bot.change_presence(game=discord.Game(name=new_game), status=current_status)
> 
> New:
>             if self.last_change == None: #first run
>                 self.last_change = int(time.perf_counter())
>                 if len(self.statuses) > 0 and (current_game in self.statuses or current_game == "None"):
>                     new_game = self.random_status(message)
>                     await self.bot.change_presence(game=discord.Game(**type=0,** name=new_game), status=current_status)

and

> Old:
>                     if new_game != None:
>                         if current_game != new_game:
>                             if current_game in self.statuses or current_game == "None": #Prevents rndstatus from overwriting song's titles or
>                                 await self.bot.change_presence(game=discord.Game(name=new_game), status=current_status) #custom statuses set with !set status
> 
> New:
>                     if new_game != None:
>                         if current_game != new_game:
>                             if current_game in self.statuses or current_game == "None": #Prevents rndstatus from overwriting song's titles or
>                                 await self.bot.change_presence(game=discord.Game(**type=0,** name=new_game), status=current_status) #custom statuses set with !set status
>

**Comment by skeith** [comment]
Even without editing the cog, rndstatus just works. You just need to update your bot requirements, then it will work

**Comment by MiniJennJenn** [comment]
#announcements on the discord channel ;)
Twentysix - Last Thursday at 7:55 AM
Updating the requirements from the launcher should fix the status issue
