### ISSUE TITLE
Triggers not working for messages sent from Discord Android app

### ISSUE THREAD

**Issue by Remiccino** [Twentysix26/26-Cogs#34]
Hello, and thanks for the great cog. As the title suggests, I'm having an issue where the bot does not trigger upon messages sent from the Android app, even though it works fine on PC. I would like this to be looked into if possible.

**Comment by Twentysix26** [comment]
I can't reproduce this. Can you provide a screenshot that shows the trigger's creation plus an attempt to trigger it from the android app?

**Comment by Remiccino** [comment]
Sorry for the trouble, but just to make sure, I pulled the lastest trigger.py manually and replaced the old one and now it's working again. Had no idea why it happened though, only lasted for today.
