### ISSUE TITLE
rift open to the public by default

### ISSUE THREAD

**Issue by Skyridr** [Twentysix26/26-Cogs#35]
For some odd reason, there are no checks in place that prevents usage of the command by the public.  I've manually added 

- from .utils import checks
- @checks.mod_or_permissions(administrator=True)

To prevent this. This command was heavily abused.

**Comment by skeith** [comment]
Twentysix response to the same concern on the support channel

![image](https://user-images.githubusercontent.com/340284/34367937-e886f69e-eaea-11e7-9a0f-ded91185cf98.png)
