### ISSUE TITLE
 Audio Cog Youtube Playlist Error

### ISSUE THREAD

**Issue by sean-james** [Twentysix26/26-Cogs#40]
Hey I'm getting an error with the audio cog when requesting a YouTube playlist. The error I get is in the Discord channel itself not sure if it's to do with any recent changes to youtube-dl

`I'm unable to play 'https://www.youtube.com/playlist' because of an error:
'ERROR: Unable to download webpage: HTTP Error 404: Not Found (caused by <HTTPError 404: 'Not Found'>); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.'`

**Comment by Twentysix26** [comment]
[Wrong repository](https://github.com/Cog-Creators/Red-DiscordBot/issues). Looks like an outdated requirements issue anyway.
