### ISSUE TITLE
[rift] riftopen is usable by everyone

### ISSUE THREAD

**Issue by Jan200101** [Twentysix26/26-Cogs#6]
This can lead to some weird moments where you bot just starts talking to you.

There have been two suggestion on how to "fix" this

1) The other server needs to accept the rift just like a phone call but both can exit it at any time

2) Making the command Mod/Admin/Owner only

**Comment by Twentysix26** [comment]
3. Use squid's permissions and set the permissions you want.  

I'm not interested in limiting it in any way
