### ISSUE TITLE
[Feature Request] More complex triggers.

### ISSUE THREAD

**Issue by ghost** [Twentysix26/26-Cogs#9]
I'd like if I put two triggers with the same word, they don't trigger at the same time.

Example : 
Trigger 1 : Waifu 
Trigger 2 : Kurisu is my waifu

I'd like if trigger 2 wouldn't be triggered at the same time as trigger 1. This way, the bot could use context instead of any word. Not sure if it's possible but I hope so.

**Comment by skeith** [comment]
That's not how trigger works. It is called trigger (verb. cause (an event or situation) to happen or exist.)

What you wanted is a custom cog

**Comment by ghost** [comment]
I want triggers to be more specific so that two triggers may not be triggered at the same time. I don't think a custom cog would be needed for this. Am I missing something?

**Comment by Twentysix26** [comment]
Nah, I understood what you meant the first time. I'm not sure if I can / want to implement this though. You can get quite advanced behavior with regex already and some users might want to trigger more than one at once. So it would have to be yet another setting.

**Comment by ghost** [comment]
I see. You'd have to give priority to longer strings to implement a feature like this if I'm not mistaken, right?
